// (C) Copyright IBM Corp. 2025,2026
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package topology

import (
	"os"
	"path/filepath"

	klog "k8s.io/klog/v2"

	"github.com/ibm-aiu/dra-driver-spyre/pkg/topology/types/pcitopo"
	utils "github.com/ibm-aiu/dra-driver-spyre/pkg/utils"
)

var (
	// DefaultTopologyFolder defines a default folder contains all nodes' topology files
	// This path is mount path from custom config map.
	DefaultTopologyFolder = "/etc/aiu/topology"
	// GeneratedTopologyFilepath defines a default path of topology file for pseudo mode
	GeneratedTopologyFilepath = "/tmp/generated-topo.json"
	// MetadataTopologyFilepath defines a path of topology file generated by init container
	MetadataTopologyFilepath = "/usr/local/etc/spyre-dra-driver/metadata/topo.json"
	// IgnoreMetadataKey set this env to `true` to skip metadata file
	IgnoreMetadataKey = "IGNORE_EXTERNAL_METADATA"
)

// GetPciTopology returns Pcitopo from topology file (topo.json),
// Check if topologyFilepath is given and valid.
// If given topologyFilepath is valid, unmarshal to Pcitopo.
// If not, use pseudo topology if pseudo mode is enabled
// If successfully unmarshal, write it to a static file.
func GetPciTopology(topologyFilepath string) (*pcitopo.Pcitopo, error) {
	pseudoMode := utils.IsPseudoDeviceMode()

	// replace empty filepath with default path
	if topologyFilepath == "" {
		topologyFilepath = GetTopologyFile()
	}
	var err error
	var s []byte
	var staticTopo bool
	if s, err = os.ReadFile(topologyFilepath); err != nil {
		if pseudoMode {
			s = []byte(PseudoTopology)
			staticTopo = true
		} else {
			return nil, err
		}
	} else {
		klog.Infof("use topology data from %s", topologyFilepath)
	}
	pcitopo, err := pcitopo.UnmarshalPciTopo(s)
	if err == nil {
		if staticTopo {
			// write a file if using static topology topologyFilepath
			if err := pcitopo.Write(topologyFilepath); err != nil {
				klog.Warningf("cannot write static topology to %s: %v", topologyFilepath, err)
			}
		}
	}
	return &pcitopo, err
}

func GetTopologyFile() string {
	// first check metadata topology filepath
	if os.Getenv(IgnoreMetadataKey) != "true" && utils.PathExists(MetadataTopologyFilepath) {
		return MetadataTopologyFilepath
	}
	pseudoMode := utils.IsPseudoDeviceMode()
	nodeName := utils.GetNodeName()
	topologyFilepath := filepath.Join(DefaultTopologyFolder, nodeName)
	if !utils.PathExists(topologyFilepath) {
		klog.Infof("topology config %s not set, use pseudo topology or generate from pcitopo", topologyFilepath)
		// no default topology defined by configmap
		if !pseudoMode {
			klog.Infof("using default topology path")
		} else if !utils.PathExists(topologyFilepath) {
			topologyFilepath = GeneratedTopologyFilepath
		}
	}
	return topologyFilepath
}
